# Generated by Django 6.0 on 2026-01-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='website_boo_user_id_77f5e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='website_boo_slot_id_9d6410_idx',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='uq_booking_slot_user',
        ),
        migrations.RemoveIndex(
            model_name='slot',
            name='website_slo_start_a_d1c71d_idx',
        ),
        migrations.RemoveIndex(
            model_name='slot',
            name='website_slo_status_5029e8_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
