# Generated by Django 6.0 on 2026-01-29 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0002_remove_booking_website_boo_user_id_77f5e3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('address', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('hidden', 'Hidden'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='timeslot_end_after_start'), models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='timeslot_capacity_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='confirmed', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslot_bookings', to=settings.AUTH_USER_MODEL)),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='website.timeslot')),
            ],
            options={
                'ordering': ['-booked_at'],
                'indexes': [models.Index(fields=['timeslot', 'status'], name='website_boo_timeslo_365978_idx'), models.Index(fields=['user', 'status'], name='website_boo_user_id_77f5e3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('timeslot', 'user'), name='uniq_confirmed_booking_per_user_timeslot')],
            },
        ),
    ]
