# Generated by Django 6.0 on 2026-01-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='event_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='event_name',
            field=models.CharField(default='event', max_length=50),
            preserve_default=False,
        ),
    ]
